### ISSUE TITLE
XSS Vulnerability

### ISSUE THREAD

**Issue by dustyfresh** [bmo-tv/bmo-google-oauth#1]
[See highlighted lines](https://github.com/bmo-tv/bmo-google-oauth/blob/master/bmo-google-oauth.php#L321-L322)

This can be fixed by using [htmlentities](http://php.net/manual/en/function.htmlentities.php):

``` php
$username = htmlentities($_GET['google-oauth-username']);
```

**Comment by BMO-tech** [comment]
The recommended fix has been added, but I'm out of the office until next Monday (06/06/2016). Because of that I haven't been able to test the fix or roll it out. These things will have to wait until then.

**Comment by BMO-tech** [comment]
Your.wpengine.com has been updated. @dustyfresh before I hand the updated plugin to everyone else, would you like to double check if this has fixed the vulnerability?

**Comment by dustyfresh** [comment]
👍 Lookin' good to me
